### ISSUE TITLE
Model weirdness with Entity Model Features

### ISSUE THREAD

**Issue by Partonetrain** [Christofmeg/JustEnoughBreeding#14]
Tested with EMI on Fabric 0.15.7 and Cubical Critters (https://modrinth.com/resourcepack/cubical-critters)

![image](https://github.com/Christofmeg/JustEnoughBreeding/assets/19861808/bccdb8d0-ac56-49ff-9961-e78238c40e58)

**Comment by Christofmeg** [comment]
@Partonetrain What minecraft version are you using and what version of the resource pack is used?

**Comment by Partonetrain** [comment]
1.20.1, resource pack v1.0, Entity Model Features 1.20.1-1.3

**Comment by Christofmeg** [comment]
I did some testing and the issue only occurs when a resourcepack changes vanilla mob models with .jem files. EMF allows you to load in .jem files from optifine. 

Tested with Optifine instead of [EMF] Entity Model Features and [ETF] Entity Texture Features and the issue went away.
That indicates that you should file a bug report on the [EMF](https://github.com/Traben-0/Entity_Model_Features/issues) github. And hopefully you can get more help there.
